force-app/main/default/objects/constructor__c/constructor__c.object-meta.xml
<CustomObject>
    <label>Constructor</label>
    <nameField>
        <label>constructor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FINAL_PROJECT/force-app/main/default/objects/constructor__c/fields/constructorId__c.field-meta.xml
<CustomField>
    <fullName>constructorId__c</fullName>
    <externalId>true</externalId>
    <label>Constructor id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/constructor__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

FINAL_PROJECT/force-app/main/default/objects/constructor__c/fields/nationality__c.field-meta.xml
<CustomField>
    <fullName>nationality__c</fullName>
    <label>Nationality</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/constructor.cls
public with sharing class  constructor {

    @AuraEnabled
    public static List<Map<String, Object>> givenConstructors() {
        List<Map<String, Object>> result = new List<Map<String, Object>>();

        try {
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:pilotos2/ergast/f1/2025/constructors.json');
            req.setMethod('GET');

            HttpResponse res = http.send(req);

            if (res.getStatusCode() == 200) {
                constructorWrapper.root data = (constructorWrapper.root) JSON.deserialize(res.getBody(), constructorWrapper.root.class);

                if (data != null && data.MRData != null && data.MRData.constructorTable != null &&
                    data.MRData.constructorTable.constructors != null && !data.MRData.constructorTable.constructors.isEmpty()) {

                 
                    for (constructorWrapper.constructor cons : data.MRData.constructorTable.constructors) {
                        Map<String,Object> row = new Map<String,Object>();
                        row.put('constructorId', cons.constructorId);
                        row.put('url', cons.url);
                        row.put('name', cons.name);
                        row.put('nationality', cons.nationality);
                        result.add(row);
                    }

                }
            } else {
                System.debug('Error en el callout: ' + res.getStatus());
            }
        } catch (Exception e) {
            System.debug('Excepción: ' + e.getMessage());
        }

        return result;
    }

    @AuraEnabled
    public static void saveConstructors() {
        List<Map<String,Object>> constructorTable = givenConstructors();
        List<constructor__c> constructorToInsert = new List<constructor__c>();

        for (Map<String,Object> cons : constructorTable) {
            constructor__c constObj = new constructor__c();
            constObj.Name = (String) cons.get('name');
            constObj.constructorId__c = (String) cons.get('constructorId');
            constObj.url__c = (String) cons.get('url');
            constObj.name__c = (String) cons.get('name');
            constObj.nationality__c = (String) cons.get('nationality');
            constructorToInsert.add(constObj);
        }

        if (!constructorToInsert.isEmpty()) {
            insert constructorToInsert;
        }
    }
}